language: c++
sudo: false
compiler: gcc
cache: 
    - ccache
    - apt
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
        - ubuntu-sdk-team
        - boost-latest
    packages:
        - freeglut3-dev 
        - libasound2-dev 
        - libxmu-dev 
        - libxxf86vm-dev 
        - g++4.9 
        - libgl1-mesa-dev
        - libglu1-mesa-dev 
        - libraw1394-dev 
        - libudev-dev 
        - libdrm-dev 
        - libglew-dev 
        - libopenal-dev 
        - libsndfile-dev 
        - libfreeimage-dev 
        - libcairo2-dev 
        - libfreetype6-dev 
        - libssl-dev 
        - libpulse-dev 
        - libusb-1.0-0-dev 
        - libgtk-3-dev  
        - libopencv-dev 
        - librtaudio-dev 
        - libboost-filesystem1.55-dev
      
env:
  matrix:
    - NAME="linux" \
        OF_ROOT="$PWD" \
        SCRIPT="scripts/linux/testTemplate.sh"
before_install: 
    - sudo scripts/linux/ubuntu/install_dependencies.sh
    - export CXX=g++-4.9
script:
    $SCRIPT
git:
    depth: 1
notifications:
    webhooks: http://192.237.185.151/web-hooks/travis_done.cgi
